name: on-commit

on:
  push:
    branches:
      - build  # Change this if needed

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: on-commit  # Ensures only one build runs at a time
      cancel-in-progress: false  # Prevents cancelling running builds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Save Previous Commit (Handle First Commit Case)
        id: previous_commit
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            echo "PREV_COMMIT=$(git rev-parse HEAD^)" >> $GITHUB_ENV
          else
            echo "PREV_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV  # Fallback to HEAD if no previous commit
          fi
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust this to your version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        
      - name: Revert Push on Failure
        if: failure()
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ "$PREV_COMMIT" = "$(git rev-parse HEAD)" ]; then
            echo "First commit detected. Cannot revert."
            exit 1
          fi

          git reset --hard $PREV_COMMIT
          git push --force https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git build
